CREATE USER IF NOT EXISTS bloxappuser@`%` IDENTIFIED BY 'passwd';
CREATE DATABASE  IF NOT EXISTS bloxapp;
GRANT ALL ON bloxapp.* TO bloxappuser@`%`;

CREATE TABLE IF NOT EXISTS bloxapp.metrics
    (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    measure VARCHAR(32) NOT NULL,
    val DOUBLE NOT NULL,
    ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP );